name: Archive Woomorrintegration content
# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        
      - name: Update version information
        run: |
          # Update the version in the JSON file
          sed -i "s/<plugin_version>/1.0.${{ github.run_number }}/g" plugin-woomorrintegration.json

      - name: Archive content
        uses: thedoctor0/zip-release@0.7.5
        with:
          filename: woomorrintegration.zip
          exclusions: '*.json *.git*'

      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./woomorrintegration.zip
          asset_name: woomorrintegration.zip
          asset_content_type: application/zip
      - name: Commit changes
        run: |
          git config --global user.email "bouras1920@gmail.com"
          git config --global user.name "GitHub Actions"
          git add plugin-woomorrintegration.json
          git commit -m "Update blog.json"
          git remote set-url origin https://taha2002:${{ secrets.GH_TOKEN }}@github.com/taha2002/woomorrintegration
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
